services:
  mariadb:
    container_name: mariadb_cont
    image: mariadb:shachowd
    restart: always
    env_file: .env
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

  wordpress:
    container_name: wordpress_cont
    image: wordpress:shachowd
    restart: always
    env_file: .env
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx_cont
    image: nginx:shachowd
    restart: always
    env_file: .env
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wp:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    #name: DB_Volume
    driver: local
    driver_opts:
      type: none
      device: /Users/shahnaj/data/db
      o: bind
  wp:
    #name: WP_Volume
    driver: local
    driver_opts:
      type: none
      device: /Users/shahnaj/data/wp
      o: bind
